### ISSUE TITLE
AllLaserDevicesGUIDemo is broken on developp

### ISSUE THREAD

**Issue by royerloic** [ClearControl/ClearControl#1]

**Comment by hkmoon** [comment]
While I am working on develop branch, ```clearcontrol.microscope.lightsheet.acquisition.LightSheetAcquisitionStateInterface``` is missing in ```NDIteratorAdaptationModule.java```

**Comment by hkmoon** [comment]
I am working on ```develop``` branch. Do not use until I provide the stable version with ```master```.
